// Generated by Haxe 3.4.7
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	console.log("Hello World");
	var _graphic = new PIXI.Graphics();
	_graphic.beginFill(16711680,0.4);
	_graphic.drawRect(200,150,400,300);
	_graphic.endFill();
};
var pixi_core_renderers_webgl_filters_CurrentState = function() { };
Main.main();
})();
